#File Version p.2025.11.19.001
services:
  caddy:
    image: caddy:${IMAGE_TAG:-latest}
    container_name: CaddyProxy
    restart: unless-stopped # I prefer unless-stopped, it make troubleshooting/maintance windows with reboots on my homelab easier to manage dozens of containers
    env_file:
      - .env
    ports:
      - 443:443
    volumes:
      - caddy-config:/config
      - caddy-data:/data
      - ./CaddyProxy/Caddyfile:/etc/caddy:ro # directory where my caddyfile is stored on host system, set to :ro (readonly) for best sec practices
      - ./CaddyProxy/CustomCerts:/PreloadedCerts:ro # this is staging to allow custom certs outside of container from is stored on host system (need to be 711 permissions and in .pem format), set to :ro (readonly) for best sec practices
    networks:
      CaddyProxyNet:
        ipv4_address: 172.200.0.200 #hard coding id, doing this for services that require a "trusted-proxy" var to be set, using static ip over range. Setting to a high value to ensure if the containers all boot out of order on host start up, that caddy can reserve an ip without a clash issue.

volumes:
  caddy-config:
    name: caddy-config #while not important for caddy, I typically like to name my volumes so its easier to ID them and remount them
  caddy-data:
    name: caddy-data

networks:
  CaddyProxyNet:
    name: CaddyProxyNet
    driver: bridge
    # external: true # uncomment in the event the network exist before hand, troubleshooting line I leave in on my compose files.
    ipam:
      config:
        - subnet: 172.200.0.0/24 #setting the ip range that can be used for this docker network